root_obs: &root_obs s3://bucket-3690/ZhouPeng
modelarts_download: &modelarts_download
  ffhq256:
    datapath_obs: '{global_cfg.root_obs}/keras/ffhq/downsample_ffhq_256x256.zip'
    datapath: "datasets/ffhq/downsample_ffhq_256x256.zip"
    overwrite: false
    eval: true
    unzip: true
  ffhq256_list:
    datapath_obs: '{global_cfg.root_obs}/keras/ffhq/ffhq_256.txt'
    datapath: "datasets/ffhq/ffhq_256.txt"
    overwrite: false
    eval: true
    unzip: false
  fid_inception:
    datapath_obs: '{global_cfg.root_obs}/keras/cache/torch/hub/checkpoints/weights-inception-2015-12-05-6726825d.pth'
    datapath: "/home/ma-user/.cache/torch/hub/checkpoints/weights-inception-2015-12-05-6726825d.pth"
    overwrite: false
    eval: true
    unzip: false


network_pkl: &network_pkl
  v6_FFHQ:  "cache_pretrained/pretrained/G_ema_celeba_converted_all.pth"
  v4_FFHQ_r128_idx_2_1_9_inr_detach: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v4/train_ffhq-20220227_232054_529/ckptdir/resume/G_ema.pth"
  v4_FFHQ_r64_idx_2_1_9_inr_detach: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v4/train_ffhq-20220225_223444_066/ckptdir/resume/G_ema.pth"
  v4_FFHQ_r128_idx_2_1_4_inr_detach: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v4/train_ffhq-20220227_232853_341/ckptdir/resume/G_ema.pth"
  v4_FFHQ_r64_idx_2_1_4_inr_detach: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v4/train_ffhq-20220225_164209_334/ckptdir/resume/G_ema.pth"
  v4_FFHQ_r128_idx_2_1_9_inr_detach_c128: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v4/train_ffhq-20220227_233438_211/ckptdir/resume/G_ema.pth"
  v4_FFHQ_r64_idx_2_1_9_inr_detach_c128: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v4/train_ffhq-20220225_225313_381/ckptdir/resume/G_ema.pth"
  v4_FFHQ_r128_idx_2_1_1_freq_shift486: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v4/train_ffhq-20220224_092021_015/ckptdir/resume/G_ema.pth"
  v4_FFHQ_r64_idx_2_1_1_freq_shift486: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v4/train_ffhq-20220223_134902_190/ckptdir/resume/G_ema.pth"
  v4_FFHQ_r256_idx_2_1_9_freq_shift30: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v4/train_ffhq_freeze_nerf-20220224_115722_103/ckptdir/resume/G_ema.pth"
  v4_FFHQ_r128_idx_2_1_1_freq_shift30: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v4/train_ffhq-20220223_104711_687/ckptdir/resume/G_ema.pth"
  v4_FFHQ_r64_idx_2_1_1_freq_shift30: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v4/train_ffhq-20220222_225039_342/ckptdir/resume/G_ema.pth"
#  v4_FFHQ_r64_shape2: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v4/train_ffhq-20220222_224654_660/ckptdir/resume/G_ema.pth"
#  v3_FFHQ_r64_b1: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v3/train_ffhq-20220221_212808_342/ckptdir/resume/G_ema.pth"
#  v3_FFHQ_r64_b3: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v3/train_ffhq-20220221_213111_543/ckptdir/resume/G_ema.pth"
#  FFHQ_r64_siren_b1_norm_d_F: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v2/train_ffhq-20220221_091857_103/ckptdir/resume/G_ema.pth"
#  FFHQ_r64_siren_b1_norm_d_T: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v2/train_ffhq-20220221_092814_741/ckptdir/resume/G_ema.pth"
#  FFHQ_r64_siren_b3: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v2/train_ffhq-20220219_211756_715/ckptdir/resume/G_ema.pth"
#  v2_FFHQ_r64_b1: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v2/train_ffhq-20220219_182559_307/ckptdir/resume/G_ema.pth"
#  FFHQ_r64: "../bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v1/train_ffhq-20220218_225857_033/ckptdir/resume/G_ema.pth"
#  FFHQ_r128: "../bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v1/train_ffhq-20220219_104511_901/ckptdir/resume/G_ema.pth"

network_pkl_model: &network_pkl_model
  FFHQ_r64_siren_b3: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v2/train_ffhq-20220219_211756_715/ckptdir/resume/G_ema_model.pth"
  FFHQ_r64_siren_b1: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp_v2/train_ffhq-20220219_182559_307/ckptdir/resume/G_ema_model.pth"
  FFHQ_r128_siren: "/home/ma-user/work/ZhouPeng/bucket_3690/results/CIPS-3D/ffhq_diffcam_exp/train_ffhq-20220217_235524_842/ckptdir/resume/G_ema_model.pth"

obs_ffhq_r256: &obs_ffhq_r256
  datapath_obs: 'keras/ffhq/downsample_ffhq_256x256.zip'
  datapath: "datasets/ffhq/downsample_ffhq_256x256.zip"
  disable: false
  overwrite: false
  unzip: false

obs_inception_v3: &obs_inception_v3
  datapath_obs: 'keras/cache/torch/hub/checkpoints/weights-inception-2015-12-05-6726825d.pth'
  datapath: "~/.cache/torch/hub/checkpoints/weights-inception-2015-12-05-6726825d.pth"
  disable: false
  overwrite: false
  unzip: false


nerf_cfg: &nerf_cfg
  shape_net_cfg:
    input_dim: 3
    hidden_dim: 256
    out_dim: 256
    N_layers: 8
  app_net_cfg:
    input_dim: 256
    hidden_dim: 256
    out_dim: 256
    N_layers: 1

mapping_shape_app_cfg: &mapping_shape_app_cfg
  base_cfg:
    z_dim: 256
    hidden_dim: 256
    N_layers: 3


inr_cfg: &inr_cfg
#  input_dim: 128
  hidden_dim: 512
  out_dim: 3
  style_dim: 512
  num_blocks: 9

mapping_inr_cfg: &mapping_inr_cfg
  z_dim: 512
  hidden_dim: 512
  base_layers: 8
  head_layers: 0
  add_norm: true
  norm_out: true

cam_cfg: &cam_cfg
  initial_fov: 12
  normalize_rays_d: true

G_cfg_3D2D: &G_cfg_3D2D
  register_modules:
  - tl2_lib.tl2.proj.pytorch.examples.cips3d.pigan_gen_celeba
  name: tl2_lib.tl2.proj.pytorch.examples.cips3d.pigan_gen_celeba.Generator_Diffcam
  nerf_cfg: *nerf_cfg
  mapping_shape_app_cfg: *mapping_shape_app_cfg
  inr_cfg: *inr_cfg
  mapping_inr_cfg: *mapping_inr_cfg
  shape_block_end_index: 8
  app_block_end_index: 1
  inr_block_end_index: 9
  inr_detach: true


G_kwargs: &G_kwargs
  psi: 1.
  nerf_kwargs:
#    near: 0.3
#    far: 1.7
#    near: 0.5
#    far: 1.5
    near: 0.88
    far: 1.12
    N_samples: 12
    N_importance: 12
    raw_noise_std: 0. # 1.0
    eps: 1.e-10
    h_stddev: 0.3
    v_stddev: 0.155
    sample_dist: 'gaussian'


_build_generator:
  G_cfg: *G_cfg_3D2D
  G_kwargs: *G_kwargs
  cam_cfg: *cam_cfg


D_cfg: &D_cfg
  register_modules:
    - exp.cips3d_inversion.models.discriminator
  name: exp.cips3d_inversion.models.discriminator.Discriminator_MultiScale_Aux
  diffaug: false
  max_size: 1024
  channel_multiplier: 2
  first_downsample: false
  stddev_group: 0
  aux_first_downsample: false

_build_discriminator:
  D_cfg: *D_cfg
#  network_pkl: cache_pretrained/cips3d/G_ema_ffhq.pth


dataset_ffhq_r256: &dataset_ffhq_r256
  register_modules:
    - "tl2.proj.pytorch.examples.dataset_stylegan3.dataset"
  name: "ImageFolderDataset_of_stylegan"
  path: 'datasets/ffhq/downsample_ffhq_256x256.zip'
  use_labels: False
  max_size: null
#  max_size: 100
  xflip: True
  resize_resolution: null
#  resize_resolution: 1024
  random_seed: 0


_setup_evaluation:
  base: train_ffhq

_gen_images:
  base: train_ffhq
  pkl_dir: "cache_pretrained/cips3d"

_save_images:
  base: train_ffhq
  network_pkl: cache_pretrained/cips3d/G_ema_ffhq.pth


train_ffhq:
  seed: 1234
  cam_cfg: *cam_cfg
  G_cfg: *G_cfg_3D2D
  D_cfg: *D_cfg
  data_cfg: *dataset_ffhq_r256
  root_obs: *root_obs
  obs_training_dataset: *obs_ffhq_r256
  obs_inception_v3: *obs_inception_v3
  G_kwargs: *G_kwargs
  # train
  use_amp_G: false
  use_amp_D: false
  gen_lr: 0.0002
  disc_lr: 0.002
  cam_lr: 0.0001
  betas: [0, 0.999]
  fixed_z_bs: 25
  total_iters: 200000
  batch_size: 4
  batch_split: 1
  img_size: 32
  num_workers: 8
  diffaug: false
  r1_lambda: 10.
  d_reg_every: 1
  train_aux_img: true
  update_aux_every: 1
  grad_clip: 10
  forward_points: 256
  grad_points: 256
  warmup_D: false
  fade_steps: 10000
  nerf_noise_disable: false
  # log
  log_every: 10
  eval_every: 500
  # eval
  del_fid_real_images: true
  num_images_real_eval: 2048
  num_images_gen_eval: 2048
  eval_batch_size: 16
  # resume
  load_G_ema: true
  reset_best_fid: false
  load_finetune: true
  finetune_dir: "keras/CIPS-3D/cache_pretrained/pretrained/G_ema_celeba_converted"


train_ffhq_freeze_nerf:
  base: train_ffhq
  train_aux_img: false
  D_cfg:
    diffaug: true
  G_cfg:
    name: exp.cips3d_inversion.models.generator_v4.Generator_Diffcam_FreezeNeRF
  diffaug: true
  gen_lr: 0.0001
  disc_lr: 0.0005
  warmup_D: true
  fade_steps: 10000
  img_size: 128
  load_nerf_ema: true
  load_finetune: true
  nerf_noise_disable: true
  finetune_dir: "results/CIPS-3D/ffhq_diffcam_exp_v4/train_ffhq-20220223_104711_687/ckptdir/resume"



eval_fid:
  base: train_ffhq
  network_pkl_obs: "keras/CIPS-3D/cache_pretrained/cips3d/G_ema_ffhq.pth"
  network_pkl: "cache_pretrained/cips3d/G_ema_ffhq.pth"
  img_size: 256
  num_images_real_eval: 50000
  num_images_gen_eval: 50000
  kid: false


interpolate_z_web:
  port: 8501
  sidebar:
    sidebar_name: "interpolate_z_web"
  model_cfg:
    register_modules:
      - exp.cips3d_inversion.models.st_web
    name: exp.cips3d_inversion.models.st_web.STModel
  mode:
    - interpolate_z_web
  interpolate_z_web:
    G_cfg: *G_cfg_3D2D
    G_kwargs: *G_kwargs
    cam_cfg: *cam_cfg
    network_pkl: *network_pkl
    default_network_pkl: v6_FFHQ
    network_pkl_model: *network_pkl_model
    default_network_pkl_model: FFHQ_r64_siren_b1
    use_network_pkl_model: false
    bs: 4
    img_size: 256
    N_samples: 5
    N_step: 20
    fps: 20
    interp_mode:
      - lerp
      - slerp
    z_mode:
      - z_shape
      - z_app
      - z_inr
    default_z_mode: z_shape
    seeds: [1, ]
    nerf_N_samples: 12
    nerf_N_importance: 12
    forward_points: 256

sampling_yaw_web:
  base: interpolate_z_web
  port: 8501
  sidebar:
    sidebar_name: "sampling_yaw_web"
  model_cfg:
    register_modules:
      - exp.cips3d_inversion.models.st_web
    name: exp.cips3d_inversion.models.st_web.STModel
  mode:
    - sampling_yaw_web
    - interpolate_z_web
  sampling_yaw_web:
    G_cfg: *G_cfg_3D2D
    G_kwargs: *G_kwargs
    cam_cfg: *cam_cfg
    network_pkl: *network_pkl
    default_network_pkl: v6_FFHQ
    network_pkl_model: *network_pkl_model
    default_network_pkl_model: FFHQ_r64_siren_b1
    use_network_pkl_model: false
    bs: 4
    img_size: 256
    fps: 20
    nerf_N_samples: 12
    nerf_N_importance: 12
    forward_points: 256
    psi: 0.9
    seeds: [1, ]
    yaw_min: 0.1
    yaw_max: 3.04
    N_step: 20